//! Shims: real files on `PATH` that delegate resolution back to pv.
//!
//! This is the whole correctness story. PHP must resolve correctly **outside
//! an interactive shell** — editors, language servers, CI runners, cron jobs,
//! git hooks and GUI apps inherit `PATH` and nothing else. A shell hook only
//! ever fires in an interactive shell, so anything launched outside one would
//! silently fall through to a system PHP, often an ancient one, with no error.
//!
//! Every generated shim carries a marker line. A version manager that deletes
//! something it did not create is unforgivable, and file identity is the only
//! reliable way to tell a pv shim from a file the user put there.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::installs;
use crate::paths;

/// Present in every generated shim; nothing without it is ever removed.
pub const MARKER: &str = "# managed-by: pv";

/// Commands pv shims when an installed version provides them.
pub const SHIMMED: &[&str] = &[
    "php",
    "php-config",
    "phpize",
    "php-fpm",
    "php-cgi",
    "phpdbg",
];

pub fn shim_body(pv: &Path, command: &str) -> String {
    format!(
        "#!/bin/sh\n\
         {MARKER}\n\
         # generated by pv — edits are overwritten on the next install\n\
         exec {} run {command} \"$@\"\n",
        quote(&pv.to_string_lossy())
    )
}

/// Single-quote for `/bin/sh`. Shim paths can contain spaces, and an unquoted
/// interpreter path turns the first space into an argument boundary.
fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// Write a shim for every command any installed version provides, and remove
/// pv-owned shims for commands that no longer exist anywhere.
pub fn sync() -> Result<Vec<String>> {
    let dir = paths::shims_dir()?;
    paths::ensure_dir(&dir)?;
    let pv = std::env::current_exe().context("could not determine pv's own path")?;

    let mut wanted: Vec<String> = Vec::new();
    for version in installs::installed()? {
        for command in installs::commands(&version)? {
            if SHIMMED.contains(&command.as_str()) && !wanted.contains(&command) {
                wanted.push(command);
            }
        }
    }
    wanted.sort();

    for command in &wanted {
        write_shim(&dir.join(command), &shim_body(&pv, command))?;
    }
    remove_orphans(&dir, &wanted)?;
    Ok(wanted)
}

fn write_shim(path: &Path, body: &str) -> Result<()> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == body
    {
        return Ok(());
    }
    if path.exists() && !is_pv_shim(path)? {
        // Someone else owns this name here. Leave it alone and let doctor say so.
        return Ok(());
    }
    std::fs::write(path, body).with_context(|| format!("could not write {}", path.display()))?;
    make_executable(path)
}

fn remove_orphans(dir: &Path, wanted: &[String]) -> Result<()> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return Ok(()),
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if wanted.iter().any(|command| command == name) {
            continue;
        }
        if is_pv_shim(&path)? {
            std::fs::remove_file(&path)
                .with_context(|| format!("could not remove {}", path.display()))?;
        }
    }
    Ok(())
}

pub fn is_pv_shim(path: &Path) -> Result<bool> {
    let Ok(body) = std::fs::read_to_string(path) else {
        return Ok(false);
    };
    Ok(body.lines().take(5).any(|line| line.trim() == MARKER))
}

fn make_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut permissions = std::fs::metadata(path)?.permissions();
    permissions.set_mode(0o755);
    std::fs::set_permissions(path, permissions)
        .with_context(|| format!("could not make {} executable", path.display()))
}

/// Whether the shim directory is on `PATH`, and whether anything shadows it.
pub struct PathStatus {
    pub shims: PathBuf,
    pub on_path: bool,
    /// Entries before the shim directory that also provide `php`.
    pub shadowed_by: Vec<PathBuf>,
}

pub fn path_status(command: &str) -> Result<PathStatus> {
    let shims = paths::shims_dir()?;
    let entries: Vec<PathBuf> = std::env::var_os("PATH")
        .map(|path| std::env::split_paths(&path).collect())
        .unwrap_or_default();

    let position = entries.iter().position(|entry| entry == &shims);
    let before = match position {
        Some(index) => &entries[..index],
        None => &entries[..],
    };
    let shadowed_by = before
        .iter()
        .map(|dir| dir.join(command))
        .filter(|candidate| candidate.is_file())
        .collect();

    Ok(PathStatus {
        shims,
        on_path: position.is_some(),
        shadowed_by,
    })
}

/// The line `pv init <shell>` emits. Prepending is the point: a shim directory
/// placed after `/usr/bin` or a package manager's prefix is silently shadowed.
pub fn init_snippet(shell: &str, shims: &Path) -> String {
    let shims = shims.to_string_lossy().to_string();
    match shell {
        "fish" => {
            format!("# pv\nif not contains {shims} $PATH\n    set -gx PATH {shims} $PATH\nend\n")
        }
        _ => format!(
            "# pv\ncase \":$PATH:\" in\n  *\":{shims}:\"*) ;;\n  *) PATH=\"{shims}:$PATH\" ;;\nesac\nexport PATH\n"
        ),
    }
}

/// The optional `cd`-time hook, appended to `pv init <shell> --hook`.
///
/// Correctness never depends on this. The shims already resolve the right PHP
/// for every process, interactive or not; the hook only moves resolution from
/// per-command to per-directory, and gives the shell a chance to say what it
/// switched to. It is opt-in for that reason — a shell hook that goes wrong
/// takes the whole shell with it, and nothing here needs it to be right.
///
/// It exports `PV_PHP_VERSION`, which outranks every file-based rule, and that
/// makes three things load-bearing.
///
/// It must run once at startup, not only on `cd`: a new shell inherits an
/// exported value from whatever directory its parent was in, and without an
/// initial run that stale value silently outranks the new shell's own
/// `.php-version`.
///
/// It must clear the variable when nothing pins a version, so the fallback
/// stays dynamic instead of freezing at whatever resolved once.
///
/// And it must not read back what it wrote. Resolution treats the environment
/// as the highest-priority pin, so a hook that resolves with its own export
/// still set sees `Environment` every time and re-pins the same value forever
/// — leave a pinned directory and the version follows you out. The hook
/// therefore tracks what it set in `_PV_HOOK_SET` and clears its own export
/// before resolving. A value it does not recognize was set by hand and is left
/// strictly alone: an explicit `PV_PHP_VERSION=8.2` in the environment
/// outranks pv, which is the whole point of an override.
pub fn hook_snippet(shell: &str, pv: &Path) -> String {
    let pv = pv.to_string_lossy().to_string();
    match shell {
        "fish" => format!(
            "\n# pv: switch on cd (optional — the shims work without it)\n\
             function _pv_hook --on-variable PWD\n    \
                 if set -q PV_PHP_VERSION\n        \
                     if test \"$PV_PHP_VERSION\" != \"$_PV_HOOK_SET\"\n            \
                         return\n        \
                     end\n    \
                 end\n    \
                 set -e PV_PHP_VERSION\n    \
                 set -l resolved ({pv} resolve --pinned-only 2>/dev/null)\n    \
                 if test -n \"$resolved\"\n        \
                     set -gx PV_PHP_VERSION $resolved\n        \
                     set -gx _PV_HOOK_SET $resolved\n    \
                 else\n        \
                     set -e _PV_HOOK_SET\n    \
                 end\n\
             end\n\
             _pv_hook\n"
        ),
        _ => format!(
            "\n# pv: switch on cd (optional — the shims work without it)\n\
             _pv_hook() {{\n  \
                 if [ -n \"${{PV_PHP_VERSION-}}\" ] && \
                    [ \"${{PV_PHP_VERSION-}}\" != \"${{_PV_HOOK_SET-}}\" ]; then\n    \
                     return 0\n  \
                 fi\n  \
                 unset PV_PHP_VERSION\n  \
                 _pv_resolved=\"$('{pv}' resolve --pinned-only 2>/dev/null)\"\n  \
                 if [ -n \"$_pv_resolved\" ]; then\n    \
                     PV_PHP_VERSION=\"$_pv_resolved\"; export PV_PHP_VERSION\n    \
                     _PV_HOOK_SET=\"$_pv_resolved\"; export _PV_HOOK_SET\n  \
                 else\n    \
                     unset _PV_HOOK_SET\n  \
                 fi\n  \
                 unset _pv_resolved\n\
             }}\n\
             if [ -n \"${{ZSH_VERSION-}}\" ]; then\n  \
                 autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook chpwd _pv_hook\n\
             elif [ -n \"${{BASH_VERSION-}}\" ]; then\n  \
                 case \"${{PROMPT_COMMAND-}}\" in\n    \
                     *_pv_hook*) ;;\n    \
                     *) PROMPT_COMMAND=\"_pv_hook${{PROMPT_COMMAND:+;$PROMPT_COMMAND}}\" ;;\n  \
                 esac\n\
             fi\n\
             _pv_hook\n"
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_execs_pv_and_forwards_arguments() {
        let body = shim_body(Path::new("/opt/pv/bin/pv"), "php");
        assert!(body.starts_with("#!/bin/sh\n"));
        assert!(body.contains(MARKER));
        assert!(body.contains("exec '/opt/pv/bin/pv' run php \"$@\"\n"));
    }

    #[test]
    fn paths_with_spaces_stay_one_word() {
        let body = shim_body(Path::new("/Users/a b/Library/pv"), "php-fpm");
        assert!(body.contains("exec '/Users/a b/Library/pv' run php-fpm \"$@\""));
    }

    #[test]
    fn single_quotes_in_a_path_do_not_break_out() {
        let body = shim_body(Path::new("/home/o'brien/pv"), "php");
        assert!(body.contains(r"exec '/home/o'\''brien/pv' run php"));
    }

    #[test]
    fn identifies_its_own_files_and_nobody_elses() {
        let dir = tempfile::tempdir().unwrap();
        let ours = dir.path().join("php");
        std::fs::write(&ours, shim_body(Path::new("/opt/pv"), "php")).unwrap();
        let theirs = dir.path().join("php-theirs");
        std::fs::write(&theirs, "#!/bin/sh\nexec /usr/bin/php \"$@\"\n").unwrap();

        assert!(is_pv_shim(&ours).unwrap());
        assert!(!is_pv_shim(&theirs).unwrap());
        assert!(!is_pv_shim(&dir.path().join("missing")).unwrap());
    }

    #[test]
    fn the_hook_runs_at_startup_and_clears_a_stale_override() {
        for shell in ["zsh", "fish"] {
            let hook = hook_snippet(shell, Path::new("/opt/pv"));
            assert!(
                hook.trim_end().ends_with("_pv_hook"),
                "{shell}: must run once at startup, or an inherited \
                 PV_PHP_VERSION outranks the new shell's own .php-version"
            );
            assert!(
                hook.contains("unset PV_PHP_VERSION") || hook.contains("set -e PV_PHP_VERSION"),
                "{shell}: must clear the override when nothing pins a version"
            );
            assert!(
                hook.contains("_PV_HOOK_SET"),
                "{shell}: must track what it set, or resolution reads back its own \
                 export as a pin and the version follows you out of the directory"
            );
        }
    }

    #[test]
    fn init_snippets_are_idempotent_and_prepend() {
        let shims = Path::new("/home/dev/.pv/shims");

        let posix = init_snippet("zsh", shims);
        assert!(posix.contains("case \":$PATH:\""), "idempotent: {posix}");
        assert!(
            posix.contains("PATH=\"/home/dev/.pv/shims:$PATH\""),
            "prepends: {posix}"
        );

        let fish = init_snippet("fish", shims);
        assert!(fish.contains("if not contains"), "idempotent: {fish}");
        assert!(
            fish.contains("set -gx PATH /home/dev/.pv/shims $PATH"),
            "prepends: {fish}"
        );
    }
}
